### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by YuchenLiu98** [Cooperx521/PyramidDrop#2]
I encounter the problem "next_visual_length = [int(cur_image_token * self.image_token_ratio_list[stage + 1]) for cur_image_token in self.image_tokens]
IndexError: list index out of range. "
I think self.image_token_ratio_list=[0.5,0.25,0.125], from stage=2, stage+1=3, whose index out of range. Do you have any idea how to solve this problem. Thanks.

**Comment by Cooperx521** [comment]
Hello, I have updated the code fix this bug. This bug is due to missing this line [model.model.image_token_ratio_list.insert(0, 1.0)](https://github.com/Cooperx521/PyramidDrop/blob/73d99e2bb49b449a350aba4e65b146b1cfd99ca1/llava/eval/model_vqa_loader.py#L96). 1.0 here means the retained ratio of image tokens in the first stage. You can directly git pull, or add this line in your own code, but don't forget to modify ```model_vqa_mmbench.py``` and ```model_vqa_science.py``` in the same place.

If there is any other issue, feel free to ask.
Thanks for your attention to our work!

**Comment by YuchenLiu98** [comment]
Thanks for your reply. The code runs successfully with the bug fixed.
